### ISSUE TITLE
css optimazation

### ISSUE THREAD

**Issue by xushiwei** [goplus/tutorial#1]
to make web page more beautiful.

**Comment by nighca** [comment]
Design: https://www.figma.com/file/XQ96xabBKTGA2EAFx9b84W/go%2B%E7%AB%99%E7%82%B9?node-id=2%3A242

Job will be done by two steps:

1. Page style adjustment, with no header & footer
2. Publish header and footer from [goplus.org](https://github.com/goplus/www/tree/master/goplus.org) as web components, then import them here

**Comment by nighca** [comment]
3. And mobile support

**Comment by nighca** [comment]
> 1. Page style adjustment, with no header & footer

done in https://github.com/goplus/tutorial/pull/6

> Publish header and footer from goplus.org as web components, then import them here

WIP

Partially done in https://github.com/goplus/www/pull/32

> 3. And mobile support

fix in https://github.com/goplus/tutorial/pull/9

**Comment by nighca** [comment]
> 1. Page style adjustment, with no header & footer

done in https://github.com/goplus/tutorial/pull/6
