### ISSUE TITLE
Force sync for pages

### ISSUE THREAD

**Issue by xushiwei** [goplus/tutorial#14]
Add a forcing-sync button. eg. Force sync https://tutorial.goplus.org/arrays when I changed https://github.com/goplus/tutorial/tree/main/116-Arrays

**Comment by nighca** [comment]
If the deployment is done automatically, the forcing-sync button will not be needed. It may be done in three ways:

1. Webhook for current deploy pipeline, which requires a service to accept request & do deploy @qiukeren 
2. Use CD tools like Github Actions, which requires a deployment script (to be executed in action process) @qiukeren 
3. Use service like vercel (which goplus.org is current using), it may require some architecture change

I think the 2nd way's the most appropriate currently.

**Comment by xushiwei** [comment]
agree.
