### ISSUE TITLE
Optimize homepage

### ISSUE THREAD

**Issue by nighca** [goplus/tutorial#25]
* More narrow link items, for more space efficient
* Explicit reading direction

**Comment by nighca** [comment]
@xushiwei 老许看这个版本怎么样，设计师觉得不够满意，还想再调整下，不过我觉得可以；你看可以的话我就先按这个版本改一下

------

<img width="881" alt="image" src="https://user-images.githubusercontent.com/1492263/173810673-e516854f-ef1e-4866-92db-e68fb7d51f8d.png">

**Comment by xushiwei** [comment]
我觉得可以
